name: Open Source Manual Approval Lifecycle

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/decoymaster/testing-pipe-web:latest

  
  human-verification:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Wait for manual intervention comment
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: decoymaster
          minimum-approvals: 1
          issue-title: "Ready to deploy commit: ${{ github.sha }}"
          issue-body: "Please review the image build. Type 'approve' in the comments to trigger localhost rollout."

  deploy-local:
    needs: human-verification 
    runs-on: self-hosted
    steps:
      - name: Update Application Container
        run: |
          docker rm -f pipeline-web-live || true
          docker pull ghcr.io/decoymaster/testing-pipe-web:latest
          docker run -d -p 8080:80 --name pipeline-web-live ghcr.io/decoymaster/testing-pipe-web:latest
          docker image prune -f
